development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: postgres
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: postgres
  password: password